### ISSUE TITLE
Error when viewing Opportunity object

### ISSUE THREAD

**Issue by MarcDBehr** [SalesforceLabs/OrgCheck#199]
**Describe the bug**
In a Winter'23 sandbox, I opened Objects and selected Opportunity and I got the following error. Other objects that I checked work fine.

The field in that appears to be throwing the error "Closed_Lost_Reason__c" has both a Controlling Field and 2 dependent fields, so I am not sure if that is what is causing the issue.

**Error trace**

```
Salesforce Information
Salesforce API Version: 55
Installed on OrgId: 00D3K000000XXXX
Type of this org: Sandbox
Current running UserId: 005f4000000nXXXXXX
Current Daily Api Requests: {"Max":5000000,"Remaining":4999780}

Navigation Information
Page: /apex/OrgCheck_Objects_VFP

System Information
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language: en-US

Issue #0: TypeError
When: Datatable: calling formula to render the content of a cell in the table
What:
Column: Using
Formula: (r) => { if (r.custom === true) { const count = helper.html.render.whatIsItUsing(r.id, object.fieldDependencies[r.id]); if (count > 0) return helper.html.render.checkbox(true) + ' ' + count; return helper.html.render.checkbox(false); } }
Property: undefined
Data: {"aggregatable":true,"aiPredictionField":false,"autoNumber":false,"byteLength":765,"calculated":false,"calculatedFormula":null,"cascadeDelete":false,"caseSensitive":false,"compoundFieldName":null,"controllerName":null,"createable":true,"custom":true,"defaultValue":null,"defaultValueFormula":null,"defaultedOnCreate":false,"dependentPicklist":false,"deprecatedAndHidden":false,"digits":0,"displayLocationInDecimal":false,"encrypted":false,"externalId":false,"extraTypeInfo":null,"filterable":true,"filteredLookupInfo":null,"formulaTreatNullNumberAsZero":false,"groupable":true,"highScaleNumber":false,"htmlFormatted":false,"idLookup":false,"inlineHelpText":null,"label":"Closed Lost Detail","length":255,"mask":null,"maskType":null,"name":"Closed_Lost_Detail__c","nameField":false,"namePointing":false,"nillable":true,"permissionable":true,"picklistValues":[],"polymorphicForeignKey":false,"precision":0,"queryByDistance":false,"referenceTargetField":null,"referenceTo":[],"relationshipName":null,"relationshipOrder":null,"restrictedDelete":false,"restrictedPicklist":false,"scale":0,"searchPrefilterable":false,"soapType":"xsd:string","sortable":true,"type":"string","unique":false,"updateable":true,"writeRequiresMasterRead":false}
Stack:
TypeError: Cannot read properties of undefined (reading 'undefined')
   at Object.formula (/apex/OrgCheck_Objects_VFP?sfdc.tabName=01r3K00000090TO&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m3K0000008mYyQAI&nonce=ad37a8ac1e515c786c17f3cbb38ef1e492d2c75c3692bf468e60b9cc4a445c96&sfdcIFrameOrigin=/>   at /resource/1663586978000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:78364
   at Array.forEach ()
   at /resource/1663586978000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:77745
   at Array.forEach ()
   at DatatableHandler.create (/resource/1663586978000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:77486)
   at Object.create (/resource/1663586978000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:10880)
   at /apex/OrgCheck_Objects_VFP?sfdc.tabName=01r3K00000090TO&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m3K0000008mYyQAI&nonce=ad37a8ac1e515c786c17f3cbb38ef1e492d2c75c3692bf468e60b9cc4a445c96&sfdcIFrameOrigin=/>   at Object.end (/resource/1663586978000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:8623)
   at AbstractProcess.fire (/resource/1663586978000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:56877)

Issue #1: TypeError
When: Datatable: calling formula to render the content of a cell in the table
What:
Column: Using
Formula: (r) => { if (r.custom === true) { const count = helper.html.render.whatIsItUsing(r.id, object.fieldDependencies[r.id]); if (count > 0) return helper.html.render.checkbox(true) + ' ' + count; return helper.html.render.checkbox(false); } }
Property: undefined
Data: {"aggregatable":true,"aiPredictionField":false,"autoNumber":false,"byteLength":765,"calculated":false,"calculatedFormula":null,"cascadeDelete":false,"caseSensitive":false,"compoundFieldName":null,"controllerName":null,"createable":true,"custom":true,"defaultValue":null,"defaultValueFormula":null,"defaultedOnCreate":false,"dependentPicklist":false,"deprecatedAndHidden":false,"digits":0,"displayLocationInDecimal":false,"encrypted":false,"externalId":false,"extraTypeInfo":null,"filterable":true,"filteredLookupInfo":null,"formulaTreatNullNumberAsZero":false,"groupable":true,"highScaleNumber":false,"htmlFormatted":false,"idLookup":false,"inlineHelpText":null,"label":"Closed Lost Detail","length":255,"mask":null,"maskType":null,"name":"Closed_Lost_Detail__c","nameField":false,"namePointing":false,"nillable":true,"permissionable":true,"picklistValues":[],"polymorphicForeignKey":false,"precision":0,"queryByDistance":false,"referenceTargetField":null,"referenceTo":[],"relationshipName":null,"relationshipOrder":null,"restrictedDelete":false,"restrictedPicklist":false,"scale":0,"searchPrefilterable":false,"soapType":"xsd:string","sortable":true,"type":"string","unique":false,"updateable":true,"writeRequiresMasterRead":false}
Stack:
TypeError: Cannot read properties of undefined (reading 'undefined')
   at Object.formula (/apex/OrgCheck_Objects_VFP?sfdc.tabName=01r3K00000090TO&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m3K0000008mYyQAI&nonce=ad37a8ac1e515c786c17f3cbb38ef1e492d2c75c3692bf468e60b9cc4a445c96&sfdcIFrameOrigin=/>   at /resource/1663586978000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:78364
   at Array.forEach ()
   at /resource/1663586978000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:77745
   at Array.forEach ()
   at DatatableHandler.create (/resource/1663586978000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:77486)
   at Object.create (/resource/1663586978000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:10880)
   at /apex/OrgCheck_Objects_VFP?sfdc.tabName=01r3K00000090TO&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m3K0000008mYyQAI&nonce=ad37a8ac1e515c786c17f3cbb38ef1e492d2c75c3692bf468e60b9cc4a445c96&sfdcIFrameOrigin=/>   at Object.end (/resource/1663586978000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:8623)
   at AbstractProcess.fire (/resource/1663586978000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:56877)

Issue #2: TypeError
When: Datatable: calling formula to render the content of a cell in the table
What:
Column: Using
Formula: (r) => { if (r.custom === true) { const count = helper.html.render.whatIsItUsing(r.id, object.fieldDependencies[r.id]); if (count > 0) return helper.html.render.checkbox(true) + ' ' + count; return helper.html.render.checkbox(false); } }
Property: undefined
Data: {"aggregatable":true,"aiPredictionField":false,"autoNumber":false,"byteLength":765,"calculated":false,"calculatedFormula":null,"cascadeDelete":false,"caseSensitive":false,"compoundFieldName":null,"controllerName":null,"createable":true,"custom":true,"defaultValue":null,"defaultValueFormula":null,"defaultedOnCreate":false,"dependentPicklist":false,"deprecatedAndHidden":false,"digits":0,"displayLocationInDecimal":false,"encrypted":false,"externalId":false,"extraTypeInfo":null,"filterable":true,"filteredLookupInfo":null,"formulaTreatNullNumberAsZero":false,"groupable":true,"highScaleNumber":false,"htmlFormatted":false,"idLookup":false,"inlineHelpText":null,"label":"Closed Lost Detail","length":255,"mask":null,"maskType":null,"name":"Closed_Lost_Detail__c","nameField":false,"namePointing":false,"nillable":true,"permissionable":true,"picklistValues":[],"polymorphicForeignKey":false,"precision":0,"queryByDistance":false,"referenceTargetField":null,"referenceTo":[],"relationshipName":null,"relationshipOrder":null,"restrictedDelete":false,"restrictedPicklist":false,"scale":0,"searchPrefilterable":false,"soapType":"xsd:string","sortable":true,"type":"string","unique":false,"updateable":true,"writeRequiresMasterRead":false}
Stack:
TypeError: Cannot read properties of undefined (reading 'undefined')
   at Object.formula (/apex/OrgCheck_Objects_VFP?sfdc.tabName=01r3K00000090TO&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m3K0000008mYyQAI&nonce=ad37a8ac1e515c786c17f3cbb38ef1e492d2c75c3692bf468e60b9cc4a445c96&sfdcIFrameOrigin=/>   at /resource/1663586978000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:78364
   at Array.forEach ()
   at /resource/1663586978000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:77745
   at Array.forEach ()
   at DatatableHandler.create (/resource/1663586978000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:77486)
   at Object.create (/resource/1663586978000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:10880)
   at /apex/OrgCheck_Objects_VFP?sfdc.tabName=01r3K00000090TO&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m3K0000008mYyQAI&nonce=ad37a8ac1e515c786c17f3cbb38ef1e492d2c75c3692bf468e60b9cc4a445c96&sfdcIFrameOrigin=/>   at Object.end (/resource/1663586978000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:8623)
   at AbstractProcess.fire (/resource/1663586978000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:56877)
```

**Comment by VinceFINET** [comment]
Hi @MarcDBehr 

Thank you for installing OrgCheck.

In the "Data" property in the stack trace you have:
```
Data: {
...
"custom":true,
...
"label":"Closed Lost Detail",
...
"length":255,
...
"name":"Closed_Lost_Detail__c"
...
}
```
But there is no "id" property (which I am using to show the dependency tree of that field).

It seems the same issue as #197 

So the solution might be straightforward if no "id" no "dependency" (it sounds like a commercial statement!)

**Comment by MarcDBehr** [comment]
How can the field not have a id? But it does look similar

**Comment by VinceFINET** [comment]
dear @MarcDBehr 

Could you perform the following **SOQL** in your org, please?
```
SELECT Id, DurableId, QualifiedApiName, DeveloperName, Label, NamespacePrefix 
FROM FieldDefinition 
WHERE EntityDefinitionId = 'Opportunity'
AND DeveloperName = 'Closed_Lost_Detail'
```

And also on **workbench / REST Explorer**, execute the following action:
```
/services/data/v54.0/sobjects/Opportunity/describe
```
And, on the response, unfold the section "fields" then "Closed_Lost_Detail__c'


Normally the "`QualifiedApiName`" in the first query SHOULD match the "`name`" in the second request.
We can setup a call if you like.

**Comment by VinceFINET** [comment]
in fact, the "`id`" is a property that OrgCheck is adding from the standard "`describe`" method.
The reason is that the **Dependency API** relies on this id and not on the name of the field...

**Comment by VinceFINET** [comment]
Ok i reproduced the issue in my org.
Do you have a custom object or a custom settings that has exactly the developerName = 'Opportunity' ???
:D 

OrgCheck is searching for additional information on the object you request with this Tooling API SOQL query:
```
SELECT DurableId, Description, NamespacePrefix, ExternalSharingModel, InternalSharingModel, 
     (SELECT Id, DurableId, QualifiedApiName FROM Fields),
     (SELECT Id, Name FROM ApexTriggers),
     (SELECT Id, MasterLabel, Description FROM FieldSets),
     (SELECT Id, Name, LayoutType FROM Layouts),
     (SELECT DurableId, Label, Max, Remaining, Type FROM Limits),
     (SELECT Id, Active, Description, ErrorDisplayField, ErrorMessage, ValidationName FROM ValidationRules),
     (SELECT Id, Name FROM WebLinks)
FROM EntityDefinition
WHERE DeveloperName = 'Opportunity' 
```

So if we get rid of the subtables in the previous query, and add some fields just to check, I suspect that when you perform that following simple query (again with Tooling API) you will get either zero records or more than one record.
```
SELECT Id, DurableId, DeveloperName, QualifiedApiName,  Description, IsIdEnabled, PublisherId, NamespacePrefix, IsCustomSetting, DetailUrl, EditDefinitionUrl, EditUrl, HelpSettingPageUrl, NewUrl
FROM EntityDefinition
WHERE DeveloperName = 'Opportunity'
```

In my case, it returns two records, one for the `Standard SObject` called `Opportunity` and one for a `Custom Metadata Type` that I created with the name "`Opportunity`".

**Comment by VinceFINET** [comment]
note to myself: using `DeveloperName` is really a bad idea. the code should use `QualifiedApiName` instead, which seems more 'unique'.

**Comment by MarcDBehr** [comment]
Running the query

```
SELECT Id, DurableId, DeveloperName, QualifiedApiName,  Description, IsIdEnabled, PublisherId, NamespacePrefix, IsCustomSetting, DetailUrl, EditDefinitionUrl, EditUrl, HelpSettingPageUrl, NewUrl
FROM EntityDefinition
WHERE DeveloperName = 'Opportunity'
```

It says there are 2 rows (but only shows one). The DeveloperName = Opportunity and the QualifiedApiName = Opportunity__hd (Description = "Historical Data for Opportunity")

**Comment by VinceFINET** [comment]
Hi @MarcDBehr 

What happens if you query the following?

```
SELECT Id, DurableId, DeveloperName, QualifiedApiName,  Description, IsIdEnabled, PublisherId, NamespacePrefix, IsCustomSetting, DetailUrl, EditDefinitionUrl, EditUrl, HelpSettingPageUrl, NewUrl
FROM EntityDefinition
WHERE DeveloperName='Opportunity'
AND PublisherId IN ('System', '<Local>')
```

**Comment by MarcDBehr** [comment]
Hi @VinceFINET - I tried it and the entire Salesforce infrastructure crashed! 
OK, fine, not really :-) 

I got back a single line

![image](https://user-images.githubusercontent.com/3748097/197526870-1435ad37-54ca-4032-90d8-10d498412976.png)

**Comment by VinceFINET** [comment]
OK i think i have find the solution then.

I was inspired by the excellent @elchacha
Indeed filtering on the `SubscriberID` makes the difference...
