### ISSUE TITLE
Error on Custom Object

### ISSUE THREAD

**Issue by vfs-esrifrance** [SalesforceLabs/OrgCheck#238]
**Describe the bug**
On Object screen, when I'm on Custom Object, the search result shows the error below.
Few informations are displayed : only some on the Custom Object ... not the same thing on Standard Object research

**To Reproduce**
Salesforce Information
Salesforce API Version: 56
Installed on OrgId: 
Type of this org: Production
Current running UserId: 
Current Daily Api Requests: {"Max":882600,"Remaining":795968}

Navigation Information
Page: /apex/OrgCheck_Objects_VFP

System Information
Language: fr

Issue #0: TypeError
Stack:
TypeError: Cannot read properties of undefined (reading 'undefined')
   at Object.preprocessing (/apex/OrgCheck_Objects_VFP?sfdc.tabName=01r4u000000xVZi:502:117)
   at /resource/1675875338000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:87934
   at Array.forEach ()
   at DatatableHandler.create (/resource/1675875338000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:87605)
   at Object.create (/resource/1675875338000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:14505)
   at /apex/OrgCheck_Objects_VFP?sfdc.tabName=01r4u000000xVZi:498:59
   at Object.end (/resource/1675875338000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:10328)
   at AbstractProcess.fire (/resource/1675875338000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:63838)
   at /resource/1675875338000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:68012

**Comment by VinceFINET** [comment]
It is strange in the information you provided, i don't see any orgid? nor userid?
```
Installed on OrgId:
Current running UserId:
```

Can you provide me this information please ?

**Comment by vfs-esrifrance** [comment]
Installed on OrgId: 00D70000000Mzeh
Current running UserId: 0054u00000843FYAAY

**Comment by VinceFINET** [comment]
So this happens around this code:
<img width="803" alt="image" src="https://user-images.githubusercontent.com/3799275/221702639-4328f1ec-60d2-4778-9e04-596d5e822e4c.png">

**Comment by VinceFINET** [comment]
so in your case fieldDependencies is undefined and r.id as well...
need to check that in the code but most importantly must understand why in your orgs these variables are undefined...

did you select a custom object that is from a package?
is it working the same if from a custom object that is created in your org directly?

same question at field level... is this error raised when some of the fields in the object you selected are part of a package?

**Comment by vfs-esrifrance** [comment]
Hello,
Standard Object without Package => OK
Standard Object with Package => N/A

Custom Object without Package => Error and no field information
Custom Object with Package => OK, and with field information

NB: when a validation rule is inactive, the value is blank instead of false ... true is on active validation rule

**Comment by tjofr** [comment]
Hello,

Same behavior here.

Steps to reproduce
Custom Objects> No Package> FirstCustom__c
Custom Metadata Types > No Package > CMT__c
Big Object > No Package > BO__b

Custom settings and Standard Objects are OK

Salesforce Information
Salesforce API Version: 56
Installed on OrgId: 00D3X000004UOgN
Type of this org: Production
Current running UserId: 0053X00000BxCPvQAN
Current Daily Api Requests: {"Max":4825000,"Remaining":4819145}

Navigation Information
Page: /apex/OrgCheck_Objects_VFP

System Information
Language: fr-FR

Issue #0: TypeError
Stack:
TypeError: Cannot read properties of undefined (reading 'undefined')
   at Object.preprocessing (/apex/OrgCheck_Objects_VFP?sfdc.tabName=01r3X000000IRTO&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m3X000000bznGQAQ&nonce=1851a5c2839b956dc5a7cd0d12c0b498977d268504571be0b8993bf86deeaf81&sfdcIFrameOrigin=/>   at /resource/1675283606000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:87934
   at Array.forEach ()
   at DatatableHandler.create (/resource/1675283606000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:87605)
   at Object.create (/resource/1675283606000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:14505)
   at /apex/OrgCheck_Objects_VFP?sfdc.tabName=01r3X000000IRTO&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m3X000000bznGQAQ&nonce=1851a5c2839b956dc5a7cd0d12c0b498977d268504571be0b8993bf86deeaf81&sfdcIFrameOrigin=/>   at Object.end (/resource/1675283606000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:10328)
   at AbstractProcess.fire (/resource/1675283606000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:63838)
   at /resource/1675283606000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:68012

Same behavior on a sandbox
Salesforce Information
Salesforce API Version: 56
Installed on OrgId: 00D5t0000008h7Z
Type of this org: Sandbox
Current running UserId: 0053X00000BxCPvQAN
Current Daily Api Requests: {"Max":5000000,"Remaining":4999788}

Navigation Information
Page: /apex/OrgCheck_Objects_VFP

System Information
Language: fr-FR

Issue #0: TypeError
Stack:
TypeError: Cannot read properties of undefined (reading 'undefined')
   at Object.preprocessing (/apex/OrgCheck_Objects_VFP?sfdc.tabName=01r3X000000IRTO&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m3X000000bznGQAQ&nonce=36c91c2b832022d7e23b052da3459aa7c29b74520dfd5f3852914b37a79e3069&sfdcIFrameOrigin=/>   at /resource/1675282624000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:87934
   at Array.forEach ()
   at DatatableHandler.create (/resource/1675282624000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:87605)
   at Object.create (/resource/1675282624000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:14505)
   at /apex/OrgCheck_Objects_VFP?sfdc.tabName=01r3X000000IRTO&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m3X000000bznGQAQ&nonce=36c91c2b832022d7e23b052da3459aa7c29b74520dfd5f3852914b37a79e3069&sfdcIFrameOrigin=/>   at Object.end (/resource/1675282624000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:10328)
   at AbstractProcess.fire (/resource/1675282624000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:63838)
   at /resource/1675282624000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:68012

**Comment by VinceFINET** [comment]
NICE !! I could reproduce the error on a personal DE.
let me find the root cause of this !!

**Comment by VinceFINET** [comment]
When i reproduce the error and debug the previous line of code.
Both `r.id` and `object.fieldDependencies` are `undefined`....

**Comment by VinceFINET** [comment]
The error comes from the filter in a SOQL query for table EntityDefinition via Tooling API.
cf. https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_entitydefinition.htm

Currently the code contains: `PublisherId IN ('System', '<Local>')`
But should be: `PublisherId IN ('System', '<local>')`
