### ISSUE TITLE
Public Group error

### ISSUE THREAD

**Issue by vfs-esrifrance** [SalesforceLabs/OrgCheck#240]
**Describe the bug**
On Public Group, error first and after it runs a long time without ending the process :(

**To Reproduce**
Salesforce Information
Salesforce API Version: 56
Installed on OrgId: 00D70000000Mzeh
Type of this org: undefined
Current running UserId: 0054u00000843FYAAY
Current Daily Api Requests: undefined

Navigation Information
Page: /apex/OrgCheck_PublicGroups_VFP

System Information
Language: fr

Issue #0: TypeError
Stack:
TypeError: Cannot read properties of undefined (reading 'name')
   at /apex/OrgCheck_PublicGroups_VFP?sfdc.tabName=01r4u000000xVaE:415:51
   at Object.iterate2 (/resource/1676295020000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:13804)
   at Object.onRecords (/apex/OrgCheck_PublicGroups_VFP?sfdc.tabName=01r4u000000xVaE:412:40)
   at onEnd (/resource/1676295020000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:6806)
   at Object.successFinalDecorator (/resource/1676295020000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:8409)
   at /resource/1676295020000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:30627

**Comment by VinceFINET** [comment]
I would assume that the error appears here:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/3799275/221709950-a824e3c5-4044-4055-abf5-68d62b63a52f.png">

That would mean that one of your public group has a "relatedId" that do not correspond to an "id" of roles.

In your browser:
- public groups are cached as PublicGroups
- roles are cached as Roles

Could you from the browser dev tools, go to the "application" tab and check for "Storage" > "Local Storage" :
- OrgCheck.Metadata.PublicGroups
- OrgCheck.Metadata.Roles

These two should be a JSON document.
And send them here (after some anonymisation of course) the text (not the image).

Example where to find Roles info is here:
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/3799275/221710839-d7b32181-993f-4651-abeb-d2a808ef1b1d.png">

and for Public Groups:
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/3799275/221710985-e2ed0a87-9dd1-4d1f-bf99-bbcffe21680f.png">

The idea for me would be to get your two JSONs and find Public Groups that have type = Role or RoleAndSub, check their related Id in the Roles json....

Thank you.

**Comment by vfs-esrifrance** [comment]
Hello,
I ran it from Classic version.
I changed to Lightning version and from Home OgCheck application I purged metadata cache and now he result on Public Groups is fine.
FYI : I had deleted some Role records

**Comment by VinceFINET** [comment]
ok so cache issue....
but the code should not raise an error in this case.

**Comment by VinceFINET** [comment]
to reproduce the issue, you need to alter the "roles" cache.
and remove part of the roles (not remove the item in the cache it will be recalculated)

**Comment by VinceFINET** [comment]
yes!! 
<img width="393" alt="image" src="https://user-images.githubusercontent.com/3799275/222268464-0ffa29ad-b477-4b4d-8453-ddf338fa74b3.png">

Issue #0: TypeError
Stack:
TypeError: Cannot read properties of undefined (reading 'name')
   at /apex/OrgCheck_PublicGroups_VFP?sfdc.tabName=01r3V0000004Ps0&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m3V000000gXlVQAU&nonce=4edb2bfb283922f67ebd2493b213a8624839cb05fa07510eaa0a48e672853208&sfdcIFrameOrigin=/>   at Object.iterate2 (/resource/1677697517000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:13804)
   at Object.onRecords (/apex/OrgCheck_PublicGroups_VFP?sfdc.tabName=01r3V0000004Ps0&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m3V000000gXlVQAU&nonce=4edb2bfb283922f67ebd2493b213a8624839cb05fa07510eaa0a48e672853208&sfdcIFrameOrigin=/>   at onEnd (/resource/1677697517000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:6806)
   at Object.successFinalDecorator (/resource/1677697517000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:8409)
   at /resource/1677697517000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:30627
