### ISSUE TITLE
Org Check - Objects - Account

### ISSUE THREAD

**Issue by jamesppowell** [SalesforceLabs/OrgCheck#253]
**Describe the bug**

time out error for account on object tab

**To Reproduce**

Please go [here](https://github.com/SalesforceLabs/OrgCheck/issues) and log an issue with the following information.

Salesforce Information
Salesforce API Version: 57
Installed on OrgId: 00D36000000JZvE
Type of this org: Production
Current running UserId: 00536000002Z2gPAAS
Current Daily Api Requests: {"Max":50535000,"Remaining":48496642}

Navigation Information
Page: /apex/OrgCheck_Objects_VFP

System Information
Language: en-US

Issue #0: TypeError
Stack:
TypeError: Cannot read properties of undefined (reading 'undefined')
   at Object.preprocessing (/apex/OrgCheck_Objects_VFP?sfdc.tabName=01r5b000000zBBA&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m5b000000vmULAAY&nonce=d9f307305e6bd563d28826a40673f6273f87a7329f497bb5a2791f698265e071&sfdcIFrameOrigin=/>   at /resource/1678301569000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:88563
   at Array.forEach ()
   at DatatableHandler.create (/resource/1678301569000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:88234)
   at Object.create (/resource/1678301569000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:14661)
   at /apex/OrgCheck_Objects_VFP?sfdc.tabName=01r5b000000zBBA&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m5b000000vmULAAY&nonce=d9f307305e6bd563d28826a40673f6273f87a7329f497bb5a2791f698265e071&sfdcIFrameOrigin=/>   at Object.end (/resource/1678301569000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:10484)
   at AbstractProcess.fire (/resource/1678301569000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:64289)
   at /resource/1678301569000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:68496

Issue #1: TypeError
Stack:
TypeError: Cannot read properties of undefined (reading 'undefined')
   at Object.preprocessing (/apex/OrgCheck_Objects_VFP?sfdc.tabName=01r5b000000zBBA&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m5b000000vmULAAY&nonce=d9f307305e6bd563d28826a40673f6273f87a7329f497bb5a2791f698265e071&sfdcIFrameOrigin=/>   at /resource/1678301569000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:88563
   at Array.forEach ()
   at DatatableHandler.create (/resource/1678301569000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:88234)
   at Object.create (/resource/1678301569000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:14661)
   at /apex/OrgCheck_Objects_VFP?sfdc.tabName=01r5b000000zBBA&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m5b000000vmULAAY&nonce=d9f307305e6bd563d28826a40673f6273f87a7329f497bb5a2791f698265e071&sfdcIFrameOrigin=/>   at Object.end (/resource/1678301569000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:10484)
   at AbstractProcess.fire (/resource/1678301569000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:64289)
   at /resource/1678301569000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:68496

**Comment by VinceFINET** [comment]
Thank you for this issue and for using OrgCheck!
I hope this issue does not block you from using the tool for other objects…

Some questions:
- Is this issue only on the same object?
- Which object is it?
- Is it a standard or a custom or an external etc. ?
- Is this object from a package with a namespace?
- This object contains custom fields from a package with a namespace?
- If a package is it a unmanaged or a managed one?

**Comment by VinceFINET** [comment]
The error is located when calling the method `preprocessing` of a `datatable` orgcheck component in the page `OrgCheck_Objects_VFP`

There are a lot of `datatable` in this page BUT only one is using the `preprocessing` method: the one that list fields of the object you selected.

From this, I can say that the error occurs on the line 282 of visualforce page OrgCheck_Objects_VFP:
```
280: preprocessing: (r) => {
281:      if (r.custom === false) return;
282:      return helper.html.render.dependencyUsage(r.id, object.fieldDependencies[r.id], ['Layout', 'ApexClass', 'Flow']);
283: },
```

For some reason in your case, the object you selected does not have a `fieldDependencies` property.

That property is set in Orgcheck.Salesforce.js script here:
<img width="699" alt="image" src="https://user-images.githubusercontent.com/3799275/225326566-a933734d-19e5-4f5a-9dff-586c8467e2ff.png">

Still need to better understand the root cause of course.

But to correct this error to be thrown, the solution would be to set the `fieldDependencies` property to an initial structure that will not break the code in `preprocessing` method. And/or to check if the property is null/defined in the `preprocessing` method.

**Comment by VinceFINET** [comment]
I just realized you mentioned in the ticket that you had the issue for Account object. :D

**Comment by jamesppowell** [comment]
Bon nuit!

Thanks for follow up. Account object has many custom fields. How / through
which process is the fieldDependencies property set for most objects? Is it
different for Account object?

Best Regards,

James Powell
***@***.***
206.414.9109
