### ISSUE TITLE
Org Check error TypeError: Cannot read properties of undefined (reading 'undefined')

### ISSUE THREAD

**Issue by Andiraee** [SalesforceLabs/OrgCheck#259]
**Describe the bug**
We get the error below when attempting to pull information on the opportunity object. 
Standard object - no package - Opportunity (api=Opportunity) - once we choose Opportunity, we get the error. 

**To Reproduce**

Salesforce Information
Salesforce API Version: 57
Installed on OrgId: 00D60000000JeA3
Type of this org: Production
Current running UserId: 00560000000omSfAAI
Current Daily Api Requests: {"Max":3305000,"Remaining":3114942}

Navigation Information
Page: /apex/OrgCheck_Objects_VFP

System Information
Language: en-US

Issue #0: TypeError
Stack:
TypeError: Cannot read properties of undefined (reading 'undefined')
   at Object.preprocessing (/apex/OrgCheck_Objects_VFP?sfdc.tabName=01r5x000000JaDB&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m5x000000Ric1AAC&nonce=baaf9bd030523dbbddfca3e1a202d0adf08a9fe5a6af597f2ce9ed78aea27999&sfdcIFrameOrigin=/>   at /resource/1679970079000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:88563
   at Array.forEach ()
   at DatatableHandler.create (/resource/1679970079000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:88234)
   at Object.create (/resource/1679970079000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:14661)
   at /apex/OrgCheck_Objects_VFP?sfdc.tabName=01r5x000000JaDB&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m5x000000Ric1AAC&nonce=baaf9bd030523dbbddfca3e1a202d0adf08a9fe5a6af597f2ce9ed78aea27999&sfdcIFrameOrigin=/>   at Object.end (/resource/1679970079000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:10484)
   at AbstractProcess.fire (/resource/1679970079000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:64289)
   at /resource/1679970079000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:68496

**Comment by Andiraee** [comment]
no longer needed.
