### ISSUE TITLE
Issue retrieving metadata for SBQQ__Quote__c (CPQ)

### ISSUE THREAD

**Issue by madjon** [SalesforceLabs/OrgCheck#268]
Salesforce Information
Salesforce API Version: 57
Installed on OrgId: 00D28000001PwUB
Type of this org: Production
Current running UserId: 00528000007bTh8AAE
Current Daily Api Requests: {"Max":396000,"Remaining":354260}

Navigation Information
Page: /apex/OrgCheck_Objects_VFP

System Information
Language: en-US

Issue #0: TypeError
Stack:
TypeError: Cannot read properties of undefined (reading 'undefined')
   at Object.preprocessing (/apex/OrgCheck_Objects_VFP?sfdc.tabName=01r8v0000008XaQ&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m8v0000008ZRLAA2&nonce=b9fb6c4e57846e8f9ef04214cefb3cbb0fa3f28a33991f2929ffaa7376641322&sfdcIFrameOrigin=/>   at /resource/1678681006000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:88563
   at Array.forEach ()
   at DatatableHandler.create (/resource/1678681006000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:88234)
   at Object.create (/resource/1678681006000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:14661)
   at /apex/OrgCheck_Objects_VFP?sfdc.tabName=01r8v0000008XaQ&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m8v0000008ZRLAA2&nonce=b9fb6c4e57846e8f9ef04214cefb3cbb0fa3f28a33991f2929ffaa7376641322&sfdcIFrameOrigin=/>   at Object.end (/resource/1678681006000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:10484)
   at AbstractProcess.fire (/resource/1678681006000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:64289)
   at /resource/1678681006000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:68496
[export.zip](https://github.com/SalesforceLabs/OrgCheck/files/11402155/export.zip)

**Comment by VinceFINET** [comment]
Hello,
Sorry to come back so late, would you be interested to see if the new version of Org Check solves your issue?
If yes go to https://docs.google.com/forms/d/12NATkaEbN3wsoP7KbO2hKzhlkWveki1AOeZ8_lVUFAc
