### ISSUE TITLE
In Beryllium, when the animation is showing the console has some error

### ISSUE THREAD

**Issue by VinceFINET** [SalesforceLabs/OrgCheck#334]
VM5565 web-client-content-script.js:2 Uncaught TypeError: Cannot use 'in' operator to search for 'animation' in undefined
    at Ye (VM5565 web-client-content-script.js:2:52351)
    at 995 (VM5565 web-client-content-script.js:2:52634)
    at n (VM5565 web-client-content-script.js:2:188918)
    at 306 (VM5565 web-client-content-script.js:2:155727)
    at n (VM5565 web-client-content-script.js:2:188918)
    at VM5565 web-client-content-script.js:2:204492
    at VM5565 web-client-content-script.js:2:444899
    at VM5565 web-client-content-script.js:2:444914
Ye @ VM5565 web-client-content-script.js:2
995 @ VM5565 web-client-content-script.js:2
n @ VM5565 web-client-content-script.js:2
306 @ VM5565 web-client-content-script.js:2
n @ VM5565 web-client-content-script.js:2
(anonyme) @ VM5565 web-client-content-script.js:2
(anonyme) @ VM5565 web-client-content-script.js:2
(anonyme) @ VM5565 web-client-content-script.js:2
VM5564 onloadwff.js:71 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at s.<anonymous> (VM5564 onloadwff.js:71:820251)
    at l (VM5564 onloadwff.js:71:800922)
    at Object.next (VM5564 onloadwff.js:71:800233)
    at n (VM5564 onloadwff.js:71:799769)

**Comment by VinceFINET** [comment]
this is not a bug from org check, one of your chrome extension is causing this !
