### ISSUE TITLE
Clicking Plug button to ask for a recompilation of these Apex classes throws error

### ISSUE THREAD

**Issue by adione** [SalesforceLabs/OrgCheck#368]
**Describe the bug**
Clicking on the plug button from Apex tab leads to error

**To Reproduce**
Open the "Org Check" app, navigate to "Apex" tab, wait for the page to load then click on the plug button --> the error is thrown.

**Additional details**
The running user has custom admin profile
We have an important code base, actually exceeding the 15MB chars limit

Salesforce Information
Salesforce API Version: 60
Installed on OrgId: 00D3E000000D160
Type of this org: Sandbox
Current running UserId: 0057Y000007i5d0QAA
Current Daily Api Requests: {"apiUsage":{"used":5838,"limit":5000000}}

Navigation Information
Page: /apex/OrgCheck_ApexComponents_VFP

Issue #0: ERROR_HTTP_414
When: While creating a promise to call a SOQL query.
What:
index: 0
queryMore: undefined
queryString: SELECT Id, Name, Body FROM ApexClass WHERE Id IN ('01p0J000004f1As','01p0J000004oyCc','01p20000000TUes','01p20000000TgGd','01p20000000TgGe','01p20000000TgGf',[...additional IDs omitted for brevity]) LIMIT 25
queryUseTooling: undefined
Stack:
ERROR_HTTP_414: Bad Message 414
reason: URI Too Long

   at r.getError (/resource/1711362539000/orgcheck__OrgCheck_SR/js/jsforce.js:1:72641)
   at /resource/1711362539000/orgcheck__OrgCheck_SR/js/jsforce.js:1:71009
   at /resource/1711362539000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229493
   at /resource/1711362539000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229521
   at MutationObserver.o (/resource/1711362539000/orgcheck__OrgCheck_SR/js/jsforce.js:1:104504)

**Comment by adione** [comment]
I guess it's a possible duplicate of  #366
