### ISSUE TITLE
Beryllium UAT phase 3: object-permissions Cannot read properties of null (reading 'IsOwnedByProfile')

### ISSUE THREAD

**Issue by VinceFINET** [SalesforceLabs/OrgCheck#396]
DATASET object-permissions TypeError: Cannot read properties of null (reading 'IsOwnedByProfile')
TypeError: Cannot read properties of null (reading 'IsOwnedByProfile')
    at eval (modules/OrgCheck/orgcheckApp.js:3:96357)
    at Array.forEach (<anonymous>)
    at eval (modules/OrgCheck/orgcheckApp.js:3:96296)
    at eval (eval at <anonymous> (https://xxxxx--orgcheck.sandbox.vf.force.com/auraFW/javascript/xxxxx/aura_prod.js:1:1), <anonymous>:3:23715)
    at en.<anonymous> (https://xxxxx--orgcheck.sandbox.vf.force.com/auraFW/javascript/xxxxx/aura_prod.js:102:63872)

**Comment by VinceFINET** [comment]
Interesting...

In the `ObjectPermissions` table you can have a `ParentId` set with a value (valid salesforce id), **BUT** the `Parent` lookup is null.

Searching that ID in permission set table does not give you anything...

Example here:
<img width="1442" alt="image" src="https://github.com/SalesforceLabs/OrgCheck/assets/3799275/d947a1e0-e8af-4cfc-937a-a50cf6a120a7">

And no, it is not in the recycle bin either...

So ignoring that usecase in the code should be the best approach.

**Comment by VinceFINET** [comment]
to test
