### ISSUE TITLE
When querying custom object data getting an error message

### ISSUE THREAD

**Issue by jdayment** [SalesforceLabs/OrgCheck#428]
On some custom objects I am getting an error when the data set is querying 

```
TypeError: i.includes is not a function
    at eval (https://worldstrides--wsdev2--orgcheck.sandbox.vf.force.com/apex/modules/orgcheck/orgcheckApp.js:1:52888)
    at Array.forEach (<anonymous>)
    at eval (https://worldstrides--wsdev2--orgcheck.sandbox.vf.force.com/apex/modules/orgcheck/orgcheckApp.js:1:52787)
    at Array.forEach (<anonymous>)
    at eval (https://worldstrides--wsdev2--orgcheck.sandbox.vf.force.com/apex/modules/orgcheck/orgcheckApp.js:1:52755)
RECIPE object Error in dataset!
```

**Comment by VinceFINET** [comment]
interesting.... what is the object that cause this error?

**Comment by jdayment** [comment]
It's a custom object I am getting this on two different ones but others
work

**Comment by VinceFINET** [comment]
do they have special stuff, like no validation rules, no trigger or something?
