### ISSUE TITLE
NUMBER_OUTSIDE_VALID_RANGE: Maximum SOQL offset allowed for apiName ApexClass is 2000

### ISSUE THREAD

**Issue by JainySilva** [SalesforceLabs/OrgCheck#448]
- What: When accessing the Apex tab is shown the bellow errors and the Apex classes analyses isn't executed.

- Steps to Reproduce: App Launcher -> choose app "Org Check" -> tab "Home" -> access internal tab "Apex".

- Errors:

TAB apex-classes NUMBER_OUTSIDE_VALID_RANGE: Maximum SOQL offset allowed for apiName ApexClass is 2000

NUMBER_OUTSIDE_VALID_RANGE: Maximum SOQL offset allowed for apiName ApexClass is 2000
    at r.getError (https://sandboxurl--orgcheck.sandbox.vf.force.com/resource/1727095983000/orgcheck__OrgCheck_SR/js/jsforce.js:1:72641)
    at eval (https://sandboxurl--orgcheck.sandbox.vf.force.com/resource/1727095983000/orgcheck__OrgCheck_SR/js/jsforce.js:1:71009)
    at eval (https://sandboxurl--orgcheck.sandbox.vf.force.com/resource/1727095983000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229493)
    at eval (https://sandboxurl--orgcheck.sandbox.vf.force.com/resource/1727095983000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229521)
    at o (https://sandboxurl--orgcheck.sandbox.vf.force.com/resource/1727095983000/orgcheck__OrgCheck_SR/js/jsforce.js:1:104504)
    at MutationObserver.<anonymous> (https://static.lightning.force.com/bra4s.sfdc-xwy4ub/auraFW/javascript/eGx3MHlRT1lEMUpQaWVxbGRUM1h0Z2hZX25NdHFVdGpDN3BnWlROY1ZGT3cyNTAuOC40LTYuNC41/aura_prod.js:92:91749)
    at e.<computed> (https://static.lightning.force.com/bra4s.sfdc-xwy4ub/auraFW/javascript/eGx3MHlRT1lEMUpQaWVxbGRUM1h0Z2hZX25NdHFVdGpDN3BnWlROY1ZGT3cyNTAuOC40LTYuNC41/aura_prod.js:46:4694)

RECIPE apex-classes Error in dataset!

DATASET apex-classes NUMBER_OUTSIDE_VALID_RANGE: Maximum SOQL offset allowed for apiName ApexClass is 2000

NUMBER_OUTSIDE_VALID_RANGE: Maximum SOQL offset allowed for apiName ApexClass is 2000
    at r.getError (https://sandboxurl--orgcheck.sandbox.vf.force.com/resource/1727095983000/orgcheck__OrgCheck_SR/js/jsforce.js:1:72641)
    at eval (https://sandboxurl--orgcheck.sandbox.vf.force.com/resource/1727095983000/orgcheck__OrgCheck_SR/js/jsforce.js:1:71009)
    at eval (https://sandboxurl--orgcheck.sandbox.vf.force.com/resource/1727095983000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229493)
    at eval (https://sandboxurl--orgcheck.sandbox.vf.force.com/resource/1727095983000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229521)
    at o (https://sandboxurl
![Org Check - Error](https://github.com/user-attachments/assets/97ee7c35-427b-44ce-b95c-86290dcbb472)
--orgcheck.sandbox.vf.force.com/resource/1727095983000/orgcheck__OrgCheck_SR/js/jsforce.js:1:104504)
    at MutationObserver.<anonymous> (https://static.lightning.force.com/bra4s.sfdc-xwy4ub/auraFW/javascript/eGx3MHlRT1lEMUpQaWVxbGRUM1h0Z2hZX25NdHFVdGpDN3BnWlROY1ZGT3cyNTAuOC40LTYuNC41/aura_prod.js:92:91749)
    at e.<computed> (https://static.lightning.force.com/bra4s.sfdc-xwy4ub/auraFW/javascript/eGx3MHlRT1lEMUpQaWVxbGRUM1h0Z2hZX25NdHFVdGpDN3BnWlROY1ZGT3cyNTAuOC40LTYuNC41/aura_prod.js:46:4694)

**Comment by VinceFINET** [comment]
Thank you for this tcket.
I can reproduce it when doing the following in an org that has a lot of apex classes:

`SELECT count(Id) FROM apexclass`
gives me `3501` --> ok

`SELECT Id FROM apexclass limit 2000 offset 0`
gives me `2000` records --> good!

`SELECT Id FROM apexclass limit 2000 offset 2000`
gives me `1501` records -->  good!

`2000 + 1501 = 3501` --> logical and good!

BUT
if i do (and it does not make any sense i know)
`SELECT Id FROM apexclass limit 2000 offset 4000`
gives me the same error as you.

Now I need to understand why the app is trying to gather more records than it should in your org.

as a start, could you @JainySilva perform the query `SELECT count(Id) FROM apexclass` and put the result here please?

**Comment by VinceFINET** [comment]
do you have by any chance exactly `4000` apexclasses ????

**Comment by JainySilva** [comment]
Hi,

In the sandbox we tested we have 11828 classes.

Best regards.

**Comment by VinceFINET** [comment]
Hello

How the same count query with the additional statement:

WHERE ManageableState IN ('installedEditable', 'unmanaged')


Le ven. 27 sept. 2024 à 21:48, JainySilva ***@***.***> a
écrit :

**Comment by VinceFINET** [comment]
I meant this query

SELECT COUNT(Id)
FROM ApexClass
WHERE ManageableState IN ('installedEditable', 'unmanaged')

**Comment by JainySilva** [comment]
Hi,

Follow:

![Org Check - Query](https://github.com/user-attachments/assets/8f420f80-02fc-4bca-9212-68bec3fcd551)

**Comment by VinceFINET** [comment]
Ok I successfully reproduce the issue. 

It happens if you have more than 2000 classes. 

I will have to implement a different “query more alternative algorithm” not using Limit and Offset

**Comment by VinceFINET** [comment]
Today the algorithm is adding a limit and offset statement with a 200 record-window   

Tomorrow I will do the same window (200 records at a time) with an additional statement Id > ‘Xxx0000000yyy’ ORDER BY Id LIMIT 200

**Comment by VinceFINET** [comment]
dear @JainySilva 

I fixed the issue in the code (branch Main direct! oh my god!) just today
I will build the package and make that fix available asap for you.

thank you for your patience.

**Comment by VinceFINET** [comment]
pushed in your org!
