### ISSUE TITLE
Getting TypeError for visual components from ORG check app in PROD 

### ISSUE THREAD

**Issue by Ramiya04** [SalesforceLabs/OrgCheck#453]
<img width="1296" alt="Screen Shot 2024-11-03 at 9 10 24 PM" src="https://github.com/user-attachments/assets/3b1c9719-c9c3-4c7e-b3e4-1b62ed9b7564">
**Describe the bug**
After installing ORGCheck app in production, clicking on Visual Components tab is giving the attached error.

**To Reproduce**
Org Check is spinning around for 1 seconds...

We really apologize for this error.

Please consider [logging a new issue](https://sfdc.co/OrgCheck-Backlog) with all information that may help to reproduce the error you have (including some red message in your browser console).

Thank you!

TAB visual-force-pages TypeError:
TypeError
    at eval (modules/orgcheck/orgcheckApp.js:3:53191)
    at Array.forEach (<anonymous>)
    at eval (modules/orgcheck/orgcheckApp.js:3:53059)
    at Proxy.forEach (<anonymous>)
    at eval (modules/orgcheck/orgcheckApp.js:3:53027)
    at eval (eval at <anonymous> (https://york--orgcheck.vf.force.com/auraFW/javascript/ZzhjQmRxMXdrdzhvS0RJMG5qQVdxQTdEcXI0cnRHWU0zd2xrUnFaakQxNXc5LjMyMC4y/aura_prod.js:105:100625), <anonymous>:3:23715)
    at en.<anonymous> (https://york--orgcheck.vf.force.com/auraFW/javascript/ZzhjQmRxMXdrdzhvS0RJMG5qQVdxQTdEcXI0cnRHWU0zd2xrUnFaakQxNXc5LjMyMC4y/aura_prod.js:105:68834)
RECIPE visual-force-pages Error in dataset!
DATASET visual-force-pages TypeError:
TypeError
    at eval (modules/orgcheck/orgcheckApp.js:3:53191)
    at Array.forEach (<anonymous>)
    at eval (modules/orgcheck/orgcheckApp.js:3:53059)
    at Proxy.forEach (<anonymous>)
    at eval (modules/orgcheck/orgcheckApp.js:3:53027)
    at eval (eval at <anonymous> (https://york--orgcheck.vf.force.com/auraFW/javascript/ZzhjQmRxMXdrdzhvS0RJMG5qQVdxQTdEcXI0cnRHWU0zd2xrUnFaakQxNXc5LjMyMC4y/aura_prod.js:105:100625), <anonymous>:3:23715)
    at en.<anonymous> (https://york--orgcheck.vf.force.com/auraFW/javascript/ZzhjQmRxMXdrdzhvS0RJMG5qQVdxQTdEcXI0cnRHWU0zd2xrUnFaakQxNXc5LjMyMC4y/aura_prod.js:105:68834)

**Comment by VinceFINET** [comment]
What a stack trace !!
I need to change that as well cause it's not easy to understand what's wrong...
BUT I will work on this.

**Comment by VinceFINET** [comment]
can you send me the orgID where you see this issue? if confidential send it to me via DM.

**Comment by VinceFINET** [comment]
@Ramiya04 any update on this one?

**Comment by Ramiya04** [comment]
Sorry, I will get back to you by Monday.Thanks,Ramiya Sent from my iPhoneOn Nov 22, 2024, at 10:36 AM, Vincent FINET ***@***.***> wrote:﻿
@Ramiya04 any update on this one?

**Comment by VinceFINET** [comment]
any feedback?

**Comment by Ramiya04** [comment]
Hi there,

This is the first time I am working on a SalesforceLab application.  So if
i give you the org ID, would you be able to log into the org or do you need
any additional information? How do you proceed with org ID at your end?

Thank you,
Ramiya

**Comment by VinceFINET** [comment]
no issue. I can't log to your org with the org id. for me it's just an information that i can use to see what was wrong with org check. If you will it's more to see further than this unreadable stack trace!

**Comment by Ramiya04** [comment]
THe org id is *00DG0000000kvNa*

This is a production environment, but it shows "Trial" environment on the
page. I've attached a screenshot. Please check.

Thanks,
Ramiya

**Comment by VinceFINET** [comment]
Ok 

Can you run the following SOQL queries using the Tooling API please:

first one:
```
SELECT COUNT(Id)
FROM ApexPage 
WHERE ManageableState IN ('installedEditable', 'unmanaged')
```

second one: 
```
SELECT NamespacePrefix, COUNT(Id)
FROM ApexPage 
WHERE ManageableState IN ('installedEditable', 'unmanaged')
GROUP BY NamespacePrefix
```

And give me the output of the two.

Thank you!

**Comment by VinceFINET** [comment]
(using the tooling api)

**Comment by Ramiya04** [comment]
Output 1: 301 counts

Output 2

NamespacePrefix

COUNT(Id)


301

**Comment by VinceFINET** [comment]
let me insert that amount of VIsualforce Pages in my test org and see if that comes from the number of pages...

**Comment by VinceFINET** [comment]
I inserted fake Visual Force Pages in my test org. 
Unfortunately, I could not reproduce the error you have.
![image](https://github.com/user-attachments/assets/cf809a27-0af5-4c44-a0c6-af2db38154bc)

**Comment by VinceFINET** [comment]
Is it possible to plan a screen share next week?

**Comment by Ramiya04** [comment]
This is working fine in a sandbox with same amount of vf page. It’s just
this org is having the issue. I think the error is related to something
else.

**Comment by Ramiya04** [comment]
Sure. I am available Tuesday, Thursday, Friday after 11am next week.

**Comment by VinceFINET** [comment]
Can you set your user in production with "Debug Mode"
<img width="547" alt="image" src="https://github.com/user-attachments/assets/3d702102-9c60-4eae-9423-b5d365db27bb">


Then launch Org Check again and see if the stacktrace can be more explicit...

**Comment by Ramiya04** [comment]
There is no debug log being generated for this issue. Attached picture is
from the inspect page.

[image: Screen Shot 2024-12-02 at 9.54.39 AM.png]

**Comment by VinceFINET** [comment]
i don't see any picture in github sorry

**Comment by Ramiya04** [comment]
Do you see it now?

**Comment by VinceFINET** [comment]
ok i had an issue raised about error in this tab only. that was due to a typo in the code.
i do hope you have the same issue here.
if so the error is corrected and will be deployed today. i will let you know.

**Comment by VinceFINET** [comment]
The new version is being pushed.

**Comment by VinceFINET** [comment]
It should be fine. could you check if ti's working fine now?

**Comment by Ramiya04** [comment]
Nope, still seeing the same error :(

**Comment by VinceFINET** [comment]
Lets connect to plan this share screen.
LinkedIn? Bluesky?

**Comment by Ramiya04** [comment]
Can we use google meet?

**Comment by VinceFINET** [comment]
Sure
Send the invite to vfinet at gmail dot com

**Comment by Ramiya04** [comment]
I didn't get the invite. What's the email address?

**Comment by VinceFINET** [comment]
vfinet at gmail dot com 
send a first invite i will propose a time if not ok for me. (my timezone is UTC+1)

**Comment by VinceFINET** [comment]
:) received and accepted!

**Comment by Ramiya04** [comment]
Thank you :)

**Comment by VinceFINET** [comment]
Thank you for the file you sent me.

So the error you have happens when the application is getting the dependencies for the visual force pages.

```
{
    "compositeResponse": [
        {
            "body": {
                "totalSize": 992,
                "done": true,
                "records": [...]
            },
            "httpHeaders": {},
            "httpStatusCode": 200,
            "referenceId": "chunk0"
        },
        {
            "body": {
                "totalSize": 989,
                "done": true,
                "records": []
            },
            "httpHeaders": {},
            "httpStatusCode": 200,
            "referenceId": "chunk100"
        },
        {
            "body": [
                {
                    "message": "An unexpected error occurred. Please include this ErrorId if you contact support: 1458909393-3355533 (1140092415)",
                    "errorCode": "UNKNOWN_EXCEPTION"
                }
            ],
            "httpHeaders": {},
            "httpStatusCode": 500,
            "referenceId": "chunk200"
        },
        {
            "body": {
                "totalSize": 19,
                "done": true,
                "records": [...]
            },
            "httpHeaders": {},
            "httpStatusCode": 200,
            "referenceId": "chunk300"
        }
    ]
}
```

In the response you have three blocks: chunk0, chunk100, chunk200 and chunk300.
All are ok (=httpStatusCode: 200) except chunk200 (=httpStatusCode: 500)

The chunk that has issue had the following query (in tooling api): 

```
SELECT MetadataComponentId, MetadataComponentName, MetadataComponentType, RefMetadataComponentId, 
RefMetadataComponentName, RefMetadataComponentType FROM MetadataComponentDependency WHERE 
RefMetadataComponentId IN (
'0660f000002r74D','066G0000002PyUB','066G00000032q2q','0660f000002atPw',
'0660f000002atPx','0660f000002atPv','0660f000002r74E','0660f000002atPy','0660f000002r5ro','0664R000002ywcw',
'0664R000002ywcn','0660f000002asi7','0660f000002asi8','0660f000002asi9','0660f000002asiA','0660f000002asiB',
'0660f000002asiC','066G0000002ylRK','066G0000002ylRL','066G0000002ylRM','066G0000002Pz7h',
'0664R000003sGwY','0664R000003sGwT','0664R000003sGwZ','0664R000002yvsq','0664R000002yvsr',
'0664R000002yvss','066G0000002Ftwe','0660f000002ataU','0660f000002ataV','0660f000002ataW','0660f000002ataX',
'0660f000002ataY','066G0000002Ttaj','066G0000002Ttak','066G0000002Ttal','066G0000002Ttam','066G0000002Ttan',
'066G0000002Ttao','066G0000002Ttap','066G0000002Ttaq','066G0000002Ttar','066G0000002Ttas',
'066G0000002Ttat','066G0000002Ttau','066G0000002Ttav','0664R000003JHiC','0664R000003JHZ0',
'0664R000002jA88','0664R000002jA89','0664R000002jA8A','0664R000002jA8B','0664R0000037LEN',
'0664R000003JFXL','066G00000032s41','066G0000002uWms','0664R000002j3iJ','0660f000002uhRO',
'0660f000002uhRP','0660f000002uhRQ','0660f000002uhRI','0660f000002uhRJ','0660f000002uhRL',
'0660f000002uhRM','0660f000002uhRN','0660f0000037ASc','066G0000002PqYB','066G0000002PG3q',
'066G0000002FrRO','066G0000002FrRP','0660f000002uhRm','066G0000002Of77','0660f000002uhRn',
'0660f000002uhRo','0660f000002uhRp','0660f000002uhRq','0660f000002uhRr','0664R000002ywT6',
'0664R000002ywT7','066G0000002ylRJ','0664R000003JHlQ','0664R000002ywQv','0664R000002ywQw',
'0664R000002ywQx','0664R000002ywQy','0664R000002ywQz','0664R000002ywR0','0664R000002ywR1',
'0664R000002ywT3','0664R000002ywT4','0664R000002ywT5','0660f000002yutm','0660f000002yutn',
'0660f000002iO32','0660f000002iO33','0660f0000032vBC','0660f000002rCxy','066G0000002f1Ht',
'0664R000003JH8q','0664R000003JGB5'
 OR MetadataComponentId IN (
'0660f000002r74D','066G0000002PyUB','066G00000032q2q','0660f000002atPw',
'0660f000002atPx','0660f000002atPv','0660f000002r74E','0660f000002atPy','0660f000002r5ro','0664R000002ywcw',
'0664R000002ywcn','0660f000002asi7','0660f000002asi8','0660f000002asi9','0660f000002asiA','0660f000002asiB',
'0660f000002asiC','066G0000002ylRK','066G0000002ylRL','066G0000002ylRM','066G0000002Pz7h',
'0664R000003sGwY','0664R000003sGwT','0664R000003sGwZ','0664R000002yvsq','0664R000002yvsr',
'0664R000002yvss','066G0000002Ftwe','0660f000002ataU','0660f000002ataV','0660f000002ataW','0660f000002ataX',
'0660f000002ataY','066G0000002Ttaj','066G0000002Ttak','066G0000002Ttal','066G0000002Ttam','066G0000002Ttan',
'066G0000002Ttao','066G0000002Ttap','066G0000002Ttaq','066G0000002Ttar','066G0000002Ttas',
'066G0000002Ttat','066G0000002Ttau','066G0000002Ttav','0664R000003JHiC','0664R000003JHZ0',
'0664R000002jA88','0664R000002jA89','0664R000002jA8A','0664R000002jA8B','0664R0000037LEN',
'0664R000003JFXL','066G00000032s41','066G0000002uWms','0664R000002j3iJ','0660f000002uhRO',
'0660f000002uhRP','0660f000002uhRQ','0660f000002uhRI','0660f000002uhRJ','0660f000002uhRL',
'0660f000002uhRM','0660f000002uhRN','0660f0000037ASc','066G0000002PqYB','066G0000002PG3q',
'066G0000002FrRO','066G0000002FrRP','0660f000002uhRm','066G0000002Of77','0660f000002uhRn',
'0660f000002uhRo','0660f000002uhRp','0660f000002uhRq','0660f000002uhRr','0664R000002ywT6',
'0664R000002ywT7','066G0000002ylRJ','0664R000003JHlQ','0664R000002ywQv','0664R000002ywQw',
'0664R000002ywQx','0664R000002ywQy','0664R000002ywQz','0664R000002ywR0','0664R000002ywR1',
'0664R000002ywT3','0664R000002ywT4','0664R000002ywT5','0660f000002yutm','0660f000002yutn',
'0660f000002iO32','0660f000002iO33','0660f0000032vBC','0660f000002rCxy','066G0000002f1Ht',
'0664R000003JH8q','0664R000003JGB5'
)
```

So if you run only this query with tooling api you will have the same error....

**Comment by Ramiya04** [comment]
Thank you for the update. I was wondering if there might be a fix for the
issue.

Also, I’m curious why this is working fine in the sandbox.

Thanks,
Ramiya

**Comment by VinceFINET** [comment]
Hello Ramiya and Happy new year!

So back to your issue.
This is an issue with the dependency api about one of the Visual Force Pages previously mentioned (with the id starting with 066).

You don't have the issue in the sandbox because the same visual force page could have not the same error in this sanbdox.

Not an easy thing to solve because I can't just by-pass the 100 ids because of one id causing the issue.
If i bypass the error you will have missing dependencies in the application.

or maybe i can just alert that for the 100 visual force i don't have any info about dependencies... i need to think which one is a better way to output this...

**Comment by VinceFINET** [comment]
Ok so now the lines where we could not get the dependencies appear with an "Error" disabled button and is not more blocking you to see the rest of the data.

Example here:
<img width="1749" alt="image" src="https://github.com/user-attachments/assets/1a151837-2400-4c05-8fbb-c6906fa90b67" />

Will be released in the next version called Boron.

**Comment by VinceFINET** [comment]
more screenshots

there is a specific rule to highlight the fact that for these items dependencies were not retreived (so that you don't assume anything else than that
<img width="1250" alt="image" src="https://github.com/user-attachments/assets/44041498-e16f-4694-8b97-561b04f2eace" />

we also have "N/A" on the referenced in column if we had an error
<img width="1760" alt="image" src="https://github.com/user-attachments/assets/2e377a08-ba12-4256-8c09-84b8cf83f2d6" />

**Comment by VinceFINET** [comment]
See #488
