### ISSUE TITLE
Receiving error when trying to view permission sets

### ISSUE THREAD

**Issue by cward-RAM** [SalesforceLabs/OrgCheck#457]
When I try to view permission sets in the Org Check app it tries to load the data but eventually runs into the error shown below:

INVALID_SESSION_ID: Session expired or invalid
    at r.getError (https://fdmgroup--fdmstaging--orgcheck.sandbox.vf.force.com/resource/1731423217000/orgcheck__OrgCheck_SR/js/jsforce.js:1:72641)
    at eval (https://fdmgroup--fdmstaging--orgcheck.sandbox.vf.force.com/resource/1731423217000/orgcheck__OrgCheck_SR/js/jsforce.js:1:71009)
    at eval (https://fdmgroup--fdmstaging--orgcheck.sandbox.vf.force.com/resource/1731423217000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229493)
    at eval (https://fdmgroup--fdmstaging--orgcheck.sandbox.vf.force.com/resource/1731423217000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229521)
    at o (https://fdmgroup--fdmstaging--orgcheck.sandbox.vf.force.com/resource/1731423217000/orgcheck__OrgCheck_SR/js/jsforce.js:1:104504)
    at MutationObserver.<anonymous> (https://fdmgroup--fdmstaging--orgcheck.sandbox.vf.force.com/auraFW/javascript/ZzhjQmRxMXdrdzhvS0RJMG5qQVdxQVZuNVJhc1EyaHA2ZTdMUkxCNEw5Y1E5LjMyMC4y/aura_prod.js:92:91773)
    at e.<computed> (https://fdmgroup--fdmstaging--orgcheck.sandbox.vf.force.com/auraFW/javascript/ZzhjQmRxMXdrdzhvS0RJMG5qQVdxQVZuNVJhc1EyaHA2ZTdMUkxCNEw5Y1E5LjMyMC4y/aura_prod.js:46:4529)

**Comment by VinceFINET** [comment]
is it because you did not use the app for a while and your token expired?
is it happening ONLY on this tab?
what happens if you reload the page and go direclty to that page after reload?

**Comment by VinceFINET** [comment]
@Bristopher-Bord please update me on this to better understand what is happening!

**Comment by VinceFINET** [comment]
any update on this one @Bristopher-Bord ?

**Comment by VinceFINET** [comment]
also can you make sure you are using the last verrsion of Org Check by upgrading the app from the appexchange. Thank you

**Comment by VinceFINET** [comment]
it seems from the error that you are not using the last version of the application.
i will let you upgrade the app from appexchange.

i assume this closes the issue.
thank you
