### ISSUE TITLE
TAB custom-fields ERROR_HTTP_400: Access Declined

### ISSUE THREAD

**Issue by ks-cohesity** [SalesforceLabs/OrgCheck#459]
**Describe the bug**
1While trying to run the custom field dependencies, getting this error.
ERROR_HTTP_400: Access Declined
   

**To Reproduce**
ERROR_HTTP_400: Access Declined
    at r.getError (https://cohesity--orgcheck.vf.force.com/resource/1730134537000/orgcheck__OrgCheck_SR/js/jsforce.js:1:72641)
    at eval (https://cohesity--orgcheck.vf.force.com/resource/1730134537000/orgcheck__OrgCheck_SR/js/jsforce.js:1:71009)
    at eval (https://cohesity--orgcheck.vf.force.com/resource/1730134537000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229493)
    at eval (https://cohesity--orgcheck.vf.force.com/resource/1730134537000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229521)
    at o (https://cohesity--orgcheck.vf.force.com/resource/1730134537000/orgcheck__OrgCheck_SR/js/jsforce.js:1:104504)
    at MutationObserver.<anonymous> (https://cohesity--orgcheck.vf.force.com/auraFW/javascript/dzlEdDRVZ1RsVXFtVkduczVYNVVfZ1ZuNVJhc1EyaHA2ZTdMUkxCNEw5Y1E5LjMyMC4y/aura_prod.js:92:91773)
    at e.<computed> (https://cohesity--orgcheck.vf.force.com/auraFW/javascript/dzlEdDRVZ1RsVXFtVkduczVYNVVfZ1ZuNVJhc1EyaHA2ZTdMUkxCNEw5Y1E5LjMyMC4y/aura_prod.js:46:4529)

**Comment by VinceFINET** [comment]
Hello there is an issue already for this symptom.
It has been fixed in #436 and will be pushed soon.

**Comment by VinceFINET** [comment]
deployed!
