### ISSUE TITLE
LWC components list crashes 

### ISSUE THREAD

**Issue by pkassios** [SalesforceLabs/OrgCheck#471]
**Describe the bug**
When navigating to "Visual Components" and then "Lightning Web Components" the application is throwing the following errors:

**To Reproduce**

`TypeError: sfdcManager.setupUrm is not a function
    at eval (https://customer-platform-5350--qaclone--orgcheck.sandbox.vf.force.com/apex/modules/orgcheck/orgcheckApp.js:5284:34)
    at eval (https://customer-platform-5350--qaclone--orgcheck.sandbox.vf.force.com/apex/modules/orgcheck/orgcheckApp.js:3825:22)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep$U (https://customer-platform-5350--qaclone--orgcheck.sandbox.vf.force.com/apex/modules/orgcheck/orgcheckApp.js:3771:76)
    at _next (https://customer-platform-5350--qaclone--orgcheck.sandbox.vf.force.com/apex/modules/orgcheck/orgcheckApp.js:3772:169)
    at eval (https://customer-platform-5350--qaclone--orgcheck.sandbox.vf.force.com/apex/modules/orgcheck/orgcheckApp.js:3772:309)
    at new Promise (<anonymous>)
    at eval (https://customer-platform-5350--qaclone--orgcheck.sandbox.vf.force.com/apex/modules/orgcheck/orgcheckApp.js:3772:96)
    at eval (https://customer-platform-5350--qaclone--orgcheck.sandbox.vf.force.com/apex/modules/orgcheck/orgcheckApp.js:3828:28)
    at Array.map (<anonymous>)`
    
    `TypeError: sfdcManager.setupUrm is not a function
    at eval (https://customer-platform-5350--qaclone--orgcheck.sandbox.vf.force.com/apex/modules/orgcheck/orgcheckApp.js:5284:34)
    at eval (https://customer-platform-5350--qaclone--orgcheck.sandbox.vf.force.com/apex/modules/orgcheck/orgcheckApp.js:3825:22)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep$U (https://customer-platform-5350--qaclone--orgcheck.sandbox.vf.force.com/apex/modules/orgcheck/orgcheckApp.js:3771:76)
    at _next (https://customer-platform-5350--qaclone--orgcheck.sandbox.vf.force.com/apex/modules/orgcheck/orgcheckApp.js:3772:169)
    at eval (https://customer-platform-5350--qaclone--orgcheck.sandbox.vf.force.com/apex/modules/orgcheck/orgcheckApp.js:3772:309)
    at new Promise (<anonymous>)
    at eval (https://customer-platform-5350--qaclone--orgcheck.sandbox.vf.force.com/apex/modules/orgcheck/orgcheckApp.js:3772:96)
    at eval (https://customer-platform-5350--qaclone--orgcheck.sandbox.vf.force.com/apex/modules/orgcheck/orgcheckApp.js:3828:28)
    at Array.map (<anonymous>)`

![image](https://github.com/user-attachments/assets/36e20d52-d381-485a-9771-466e9619159f)

**Comment by VinceFINET** [comment]
well done.

**Comment by VinceFINET** [comment]
Deployed !
